baseurl: /
languageCode: zh-CN
title: A Hugo website
theme: "hugo-paged"
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: "/about/"
      weight: 1
    - name: Statistics
      url: "/Stat/"
      weight: 3
    - name: Bioinfo
      url: "/Bio/"
      weight: 4
    - name: Internet
      url: "/Internet/"
      weight: 5
    - name: Finance
      url: "/Finance/"
      weight: 6
    - name: Causerie
      url: "/Causerie/"
      weight: 2
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: no
